apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - image: tutum/hello-world
        name: weather
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "10m"
            memory: "10Mi"
          requests:
            cpu: "10m"
            memory: "10Mi"
            
# monolith
# scale up / down  kubectl scale --replicas=2 deploy weather
# autoscale  kubectl autoscale --min 2 --max 5 deploy weather   (metrics-server should be running in the cluster)
